### ISSUE TITLE
Conflict & DB error/missing

### ISSUE THREAD

**Issue by esdeath11** [Rizqi05/PBO-B-Kel1#1]
![image](https://user-images.githubusercontent.com/48850021/122665380-09ef9b80-d1d1-11eb-9f1f-a384c31ae05a.png)
![image](https://user-images.githubusercontent.com/48850021/122665388-12e06d00-d1d1-11eb-83ac-9431edd01514.png)

**Comment by handikacatur** [comment]
Nganu mas
